/*
 * This file was automatically generated by EvoSuite
 * Thu May 11 09:27:24 GMT 2017
 */

package edu.osu.cs362;

import org.junit.Test;
import edu.osu.cs362.CalendarMain;

public class CalendarMain_ESTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      //System.setCurrentTimeMillis((-1819L));
      String[] stringArray0 = new String[4];
      CalendarMain calendarMain0 = new CalendarMain();
      // Undeclared exception!
      //try {
        CalendarMain.main(stringArray0);
        //fail("Expecting exception: System.SystemExitException");
      
      //} catch(System.SystemExitException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         //assertThrownBy("org.evosuite.runtime.System", e);
      //}
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CalendarMain calendarMain0 = new CalendarMain();
  }
}
